apply plugin: 'com.android.application'

android {
    namespace 'com.tukokadi.app'
    compileSdk 34

    defaultConfig {
        applicationId "com.tukokadi.app"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }
}

repositories {
    google()
    mavenCentral()
}

dependencies {
    implementation 'com.squareup.okhttp3:okhttp:4.12.0'
}
